apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: my-php
        image: akdevopscoaching/myphp
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: php-app-svc
spec:
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
